- name: Create queues
  when: "'primary' in mq_role and create_queues|bool"
  block:
    - name: Generate our templated command files 
      become_user: mqm
      ansible.builtin.template:
        src: templates/create_queue.in.j2
        dest: /tmp/{{ qm.0.name }}.in
        mode: 0755
      register: template_create
      loop: "{{ queuemgrs| subelements('extra_queues', 'skip_missing=True') }}"
      loop_control:
        loop_var: qm
        label: qm.0.name

    - debug:
        var: queuemgrs
        verbosity: 1

    - name: Create the Queues
      when: template_create.changed
      failed_when: 
        - queue_create_out.rc != 0
        - queue_create_out.rc != 10 
        - "'No commands have a syntax error.' not in queue_create_out.stdout_lines"
      changed_when: queue_create_out.rc == 0
      become_user: mqm
      shell: "/opt/mqm/bin/runmqsc -f /tmp/{{ qm.name }}.in {{ qm.name }}"
      register: queue_create_out
      loop: "{{ queuemgrs }}"
      loop_control:
        loop_var: qm
        label: qm

    - name: Dump the queue_create_out
      debug:
        var: queue_create_out
        verbosity: 1

    - name: Clean up the template
      become_user: mqm
      ansible.builtin.file:
        path: /tmp/{{ qm.name }}.in
        state: absent
      loop: "{{ queuemgrs }}"
      loop_control:
        loop_var: qm
        label: qm