- name: Set fact for Linux as our OS
  when: "'rhel' in os or 'centos' in os"
  set_fact:
    ouros: "linux"

- name: Set fact for Ubuntu as our OS
  when: "'ubuntu' in os"
  set_fact:
    ouros: "ubuntu"

- name: Set fact for our package name
  when: "package is undefined or package|length == 0"
  set_fact:
    package: "mqadv_dev{{ version | replace('.', '') }}_{{ ouros }}_x86-64.tar.gz" 

- name: Download MQ Advanced for Developers
  get_url:
    url: "{{ mq_dl_url }}/{{ package }}"
    dest: /tmp/mq.tar.gz
    force: no
  tags: download

- name: Extract MQ fom TAR
  unarchive:
    src: /tmp/mq.tar.gz
    remote_src: yes
    dest: /tmp
  tags: download