- name: Start RDQM
  shell: "strmqm {{ item }}"
  changed_when: false
  loop: "{{ queue_managers }}"
  tags: startmq
  when: "'primary' in mq_role"

- name: Check RDQM Status
  shell: "dspmq"
  register: mq_status
  tags: status
  when: "'primary' in mq_role"

- debug:
    var: mq_status.stdout_lines
